INC_DIRS = \
    ./src \
    ./include

LIB_DIRS = \
    ./include
    
SRC_DIR = \
    ./src
    
PROJECT_NAME = OGL-program
MAIN_CXX = main
GLAD_CXX = glad-460

# Compile with debug symbols
#USERCPPFLAGS = -g -Wall

include ./Makefile.master
