INC_DIRS = \
    ./src \
    ./include

LIB_DIRS = \
    ./include
    
SRC_DIR = \
    ./src
    
PROJECT_NAME = OGL-program
MAIN_CXX = main
GLAD_CXX = glad-460
SHADER_CXX = Shader
MESH_CXX = SimpleMesh

# Define object files list
OBJ_LIST = $(BUILD_DIR)/$(GLAD_CXX).o $(BUILD_DIR)/$(MAIN_CXX).o $(BUILD_DIR)/$(SHADER_CXX).o $(BUILD_DIR)/$(MESH_CXX).o

# Compile with debug symbols
#USERCPPFLAGS = -g -Wall

include ./Makefile.master